name: Build And Commit Fontaweswimm

on:
  workflow_dispatch:
  pull_request:

jobs:
  should_run_commit_test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Is changed files in glyphs
        id: should-run-commit
        uses: tj-actions/changed-files@v35.4.4
        with:
          files: |
            src/glyphs/**
    outputs:
      should_run_commit: ${{ steps.should-run-commit.outputs.any_modified == 'true' || github.event_name == 'workflow_dispatch' }}

  build_and_commit_font:
    runs-on: macos-latest
    needs: should_run_commit_test
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Brew Install
        shell: bash
        run: brew install fontforge
      - name: Chmod the script
        shell: bash
        run: chmod +x src/scripts/icons2fontaweswimm/icons2fontaweswimm.py
      - name:  Build fonts
        shell: bash
        run: fontforge -script src/scripts/icons2fontaweswimm/icons2fontaweswimm.py src/scripts/icons2fontaweswimm/config/config.json src/glyphs/ src/scripts/icons2fontaweswimm/templates -o src/fonts/fontaweswimm
      - name: Commit changes
        if: ${{ always() && needs.should_run_commit_test.outputs.should_run_commit == 'true' }}
        uses: EndBug/add-and-commit@v4
        with:
          message: "Automatically build Fontaweswimm!"
          add: "."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
